# SPDX-License-Identifier: GPL-2.0-or-later
"""Readers for the id Tech 3 content formats a static closure check needs.

Every rule here is taken from the pinned ioquake3 checkout rather than from
folklore: the image and sound extension fallbacks come from `R_LoadImage` and
`S_CodecGetSound`, the shader precedence from `ScanAndLoadShaderFiles`, and the
BSP and MD3 layouts from `qfiles.h`. Nothing in this module reads the network,
the filesystem or the clock; callers hand it bytes.
"""

from __future__ import annotations

import re
import struct
from dataclasses import dataclass, field

# renderergl1/tr_image.c: R_LoadImage tries the name's own extension first and
# then every loader in this order with the extension stripped.
IMAGE_EXTENSIONS = ("tga", "jpg", "jpeg", "png", "pcx", "bmp", "pvr")

# client/snd_codec.c: S_CodecRegister prepends, so the registration order in
# S_CodecInit (opus, ogg, wav) is searched as wav, ogg, opus.
SOUND_EXTENSIONS = ("wav", "ogg", "opus")

# renderercommon/tr_common.h and tr_shader.c: these stage image names are
# generated by the renderer and never resolve to a packaged file.
GENERATED_IMAGE_NAMES = frozenset(
    {
        "$dlight",
        "$lightmap",
        "$whiteimage",
        "*white",
        "_white",
        "noimage",
        # tr_bsp.c writes this name into the shader lump entry of a surface that
        # has no shader; tr_shader.c answers it with the built-in default.
        "noshader",
    }
)


def is_engine_path(reference: str) -> bool:
    """Return whether a reference can name a file inside a PK3 at all.

    MD3 and shader files written by level editors sometimes carry an absolute
    Windows path or a bare material name. The engine looks those up too and
    falls back to its default shader, so they are real references, but they can
    never resolve to a packaged member and must not be mistaken for one.
    """
    return bool(reference) and "\\" not in reference and ":" not in reference


# qcommon/qfiles.h: BSP_VERSION for the Quake III format the pinned engine reads.
BSP_IDENT = b"IBSP"
BSP_VERSION = 46
BSP_LUMP_ENTITIES = 0
BSP_LUMP_SHADERS = 1
BSP_LUMP_COUNT = 17
BSP_SHADER_RECORD = 72

MD3_IDENT = b"IDP3"
MD3_VERSION = 15
MD3_MAX_QPATH = 64


class AssetFormatError(ValueError):
    """Raised when a content file does not match the format the engine reads."""


def _cstring(raw: bytes) -> str:
    return raw.split(b"\0", 1)[0].decode("latin-1")


@dataclass(frozen=True)
class BspInfo:
    shaders: tuple[str, ...]
    entities: tuple[dict[str, str], ...]


def parse_bsp(data: bytes) -> BspInfo:
    """Return the shader references and entity dictionaries of a Quake III BSP."""
    header = 8 + BSP_LUMP_COUNT * 8
    if len(data) < header or data[:4] != BSP_IDENT:
        raise AssetFormatError("not an IBSP file")
    (version,) = struct.unpack_from("<i", data, 4)
    if version != BSP_VERSION:
        raise AssetFormatError(f"unsupported BSP version {version}")
    lumps = [
        struct.unpack_from("<ii", data, 8 + index * 8)
        for index in range(BSP_LUMP_COUNT)
    ]
    shader_offset, shader_length = lumps[BSP_LUMP_SHADERS]
    if shader_length % BSP_SHADER_RECORD:
        raise AssetFormatError("shader lump is not a whole number of records")
    if shader_offset < 0 or shader_offset + shader_length > len(data):
        raise AssetFormatError("shader lump is outside the file")
    shaders = []
    for index in range(shader_length // BSP_SHADER_RECORD):
        start = shader_offset + index * BSP_SHADER_RECORD
        name = _cstring(data[start : start + MD3_MAX_QPATH])
        if name:
            shaders.append(name)
    entity_offset, entity_length = lumps[BSP_LUMP_ENTITIES]
    if entity_offset < 0 or entity_offset + entity_length > len(data):
        raise AssetFormatError("entity lump is outside the file")
    entity_text = data[entity_offset : entity_offset + entity_length].decode("latin-1")
    return BspInfo(tuple(shaders), tuple(parse_entities(entity_text)))


_ENTITY_PAIR = re.compile(r'"([^"]*)"\s*"([^"]*)"')


def parse_entities(text: str) -> list[dict[str, str]]:
    """Return the `{ "key" "value" }` blocks of a BSP entity lump."""
    entities = []
    for block in re.findall(r"\{([^{}]*)\}", text.split("\0", 1)[0]):
        entities.append({key: value for key, value in _ENTITY_PAIR.findall(block)})
    return entities


def parse_md3(data: bytes) -> list[str]:
    """Return the shader names referenced by every surface of an MD3 model."""
    if len(data) < 108 or data[:4] != MD3_IDENT:
        raise AssetFormatError("not an IDP3 file")
    (version,) = struct.unpack_from("<i", data, 4)
    if version != MD3_VERSION:
        raise AssetFormatError(f"unsupported MD3 version {version}")
    num_surfaces, _num_skins = struct.unpack_from("<ii", data, 84)
    (surface_offset,) = struct.unpack_from("<i", data, 100)
    shaders: list[str] = []
    for _ in range(num_surfaces):
        if surface_offset + 108 > len(data):
            raise AssetFormatError("surface header is outside the file")
        if data[surface_offset : surface_offset + 4] != MD3_IDENT:
            raise AssetFormatError("surface is not an IDP3 record")
        num_shaders = struct.unpack_from("<i", data, surface_offset + 76)[0]
        shader_offset = struct.unpack_from("<i", data, surface_offset + 92)[0]
        end_offset = struct.unpack_from("<i", data, surface_offset + 104)[0]
        for index in range(num_shaders):
            start = surface_offset + shader_offset + index * (MD3_MAX_QPATH + 4)
            if start + MD3_MAX_QPATH > len(data):
                raise AssetFormatError("shader record is outside the file")
            name = _cstring(data[start : start + MD3_MAX_QPATH])
            if name:
                shaders.append(name)
        if end_offset <= 0:
            raise AssetFormatError("surface has a non-advancing size")
        surface_offset += end_offset
    return shaders


def parse_skin(text: str) -> list[str]:
    """Return the shader names a `.skin` file maps its surfaces to."""
    shaders = []
    for line in text.splitlines():
        line = line.split("//", 1)[0].strip()
        if "," not in line:
            continue
        surface, shader = line.split(",", 1)
        shader = shader.strip()
        # cgame/cg_players.c skips tag_ surfaces and blank assignments.
        if shader and not surface.strip().lower().startswith("tag_"):
            shaders.append(shader)
    return shaders


def strip_comments(text: str) -> str:
    """Remove `//` and `/* */` comments the way COM_Parse does."""
    text = re.sub(r"/\*.*?\*/", " ", text, flags=re.DOTALL)
    return re.sub(r"//[^\n]*", "", text)


@dataclass(frozen=True)
class ShaderDefinition:
    name: str
    body: str
    images: tuple[str, ...] = field(default=())


_SKY_SIDES = ("bk", "dn", "ft", "lf", "rt", "up")


def _stage_images(body: str) -> list[str]:
    """Return the images a shader body loads, per `renderergl1`'s ParseStage."""
    images: list[str] = []
    for line in body.splitlines():
        tokens = line.replace("\t", " ").strip().split()
        if not tokens:
            continue
        directive = tokens[0].lower()
        if directive in ("map", "clampmap", "videomap") and len(tokens) >= 2:
            images.append(tokens[1])
        elif directive == "animmap" and len(tokens) >= 3:
            images.extend(tokens[2:])
        elif directive == "skyparms" and len(tokens) >= 2 and tokens[1] != "-":
            base = tokens[1]
            images.extend(f"{base}_{side}" for side in _SKY_SIDES)
    return [image for image in images if image.lower() not in GENERATED_IMAGE_NAMES]


def parse_shader_file(text: str) -> list[ShaderDefinition]:
    """Return the shader definitions of one `scripts/*.shader` file, in order."""
    text = strip_comments(text)
    definitions: list[ShaderDefinition] = []
    index = 0
    length = len(text)
    while index < length:
        while index < length and text[index].isspace():
            index += 1
        start = index
        while index < length and not text[index].isspace() and text[index] != "{":
            index += 1
        name = text[start:index].strip()
        while index < length and text[index].isspace():
            index += 1
        if index >= length or text[index] != "{":
            if not name:
                break
            # A name without a body is a malformed trailing token; stop rather
            # than silently resynchronising on unrelated text.
            raise AssetFormatError(f"shader {name!r} has no body")
        depth = 0
        body_start = index
        while index < length:
            if text[index] == "{":
                depth += 1
            elif text[index] == "}":
                depth -= 1
                if depth == 0:
                    index += 1
                    break
            index += 1
        if depth != 0:
            raise AssetFormatError(f"shader {name!r} has an unterminated body")
        body = text[body_start:index]
        if name:
            definitions.append(
                ShaderDefinition(
                    name=name, body=body, images=tuple(_stage_images(body))
                )
            )
    return definitions


def shader_file_precedence(paths: list[str]) -> list[str]:
    """Return the order in which shader definitions win, for *this* pack.

    `ScanAndLoadShaderFiles` does not sort. It concatenates the files in the
    reverse of the order `FS_ListFiles` returns them, and
    `FindShaderInShaderText` takes the first definition it meets, so a file
    later in the listing wins. `FS_SortFileList` is only used by directory
    listing and command completion, not here.

    Reverse-alphabetical is therefore the right model only because
    `content_pack.write_pk3` stores members sorted by path, which makes the
    listing of this pack alphabetical. A pack built by some other writer would
    need its own listing order, and this function would be wrong for it.
    """
    return sorted(paths, key=lambda path: path.lower(), reverse=True)


def parse_key_value_blocks(text: str) -> list[dict[str, str]]:
    """Return the `{ key "value" }` blocks used by `.arena` and `bots.txt`."""
    text = strip_comments(text)
    blocks = []
    for block in re.findall(r"\{([^{}]*)\}", text):
        record: dict[str, str] = {}
        for key, value in re.findall(r'(\w+)\s+"([^"]*)"', block):
            record[key.lower()] = value
        if record:
            blocks.append(record)
    return blocks


def parse_animation_cfg(text: str) -> dict[str, str]:
    """Return the `sex` and `footsteps` settings `cg_players.c` reads."""
    settings: dict[str, str] = {}
    for line in strip_comments(text).splitlines():
        tokens = line.replace("\t", " ").split()
        if len(tokens) >= 2 and tokens[0].lower() in ("sex", "footsteps"):
            settings[tokens[0].lower()] = tokens[1]
    return settings


def candidate_paths(reference: str, extensions: tuple[str, ...]) -> list[str]:
    """Return the file names the engine tries for one extension-less reference.

    Both `R_LoadImage` and `S_CodecGetSound` try the reference's own extension
    first and then re-try every known extension against the stripped name, so a
    reference resolves if any of these exists.
    """
    reference = reference.replace("\\", "/").lstrip("/")
    candidates = []
    if "." in reference.rsplit("/", 1)[-1]:
        candidates.append(reference)
        stem = reference.rsplit(".", 1)[0]
    else:
        stem = reference
    for extension in extensions:
        candidate = f"{stem}.{extension}"
        if candidate not in candidates:
            candidates.append(candidate)
    return candidates
